using CqmSolution.CcdaExtensions.R2;
using System.IO;
using System.Xml.Serialization;
using Xunit;

namespace CqmSolution.CcdaExtensions.Tests.R2
{
    /// <summary>
    /// Testing the classes generated by xsd cda_sdtc.xsd  SDTC.xsd /classes
    /// </summary>
    public class ClientCcdaExtensionsTests
    {
        //
        // TODO: Get some more Client test data that's in CCDA v2.x format.  2.xml and 3.xml are both v1.1, and the Client data in 4.xml - 9.xml is all copied from 1.xml.
        //

        [Theory]
        [XmlDocumentData("TestData/CCD/1.xml", "F7137007-6385-4DE4-AFE3-32B93799221B", "ClientID: F7137007-6385-4DE4-AFE3-32B93799221B (1.xml)")]
        public void GetClientSetsClientIdentifier(string path, string expected, string testName)
        {
            var serializer = new XmlSerializer(typeof(POCD_MT000040ClinicalDocument));
            var reader = new StreamReader(path);

            var doc = (POCD_MT000040ClinicalDocument)serializer.Deserialize(reader);

            var client = doc.GetClient();
            Assert.Equal(expected, client.ClientIdentifier);
        }

        [Theory]
        [XmlDocumentData("TestData/CCD/1.xml", "FirstName", "FirstName (1.xml)")]
        public void GetClientSetsFirstName(string path, string expected, string testName)
        {
            var serializer = new XmlSerializer(typeof(POCD_MT000040ClinicalDocument));
            var reader = new StreamReader(path);

            var doc = (POCD_MT000040ClinicalDocument)serializer.Deserialize(reader);

            var client = doc.GetClient();
            Assert.Equal(expected, client.FirstName);
        }

        [Theory]
        [XmlDocumentData("TestData/CCD/1.xml", "LastName", "LastName (1.xml)")]
        public void GetClientSetsLastName(string path, string expected, string testName)
        {
            var serializer = new XmlSerializer(typeof(POCD_MT000040ClinicalDocument));
            var reader = new StreamReader(path);

            var doc = (POCD_MT000040ClinicalDocument)serializer.Deserialize(reader);

            var client = doc.GetClient();
            Assert.Equal(expected, client.LastName);
        }

        [Theory]
        [XmlDocumentData("TestData/CCD/1.xml", "19540101", "Date Of Birth: Jan 01 1954 (1.xml)")]
        public void GetClientSetsDateOfBirth(string path, string expected, string testName)
        {
            var serializer = new XmlSerializer(typeof(POCD_MT000040ClinicalDocument));
            var reader = new StreamReader(path);

            var doc = (POCD_MT000040ClinicalDocument)serializer.Deserialize(reader);

            var client = doc.GetClient();
            Assert.Equal(expected, client.DateOfBirth?.Value);
        }

        [Theory]
        [XmlDocumentData("TestData/CCD/1.xml", "2.16.840.1.113883.5.1", null, "M", null, "Male", "Gender: Male (1.xml)")]
        public void GetClientSetsGender(string path, string cs, string csName, string code, string nullFlavor, string displayName, string testName)
        {
            var serializer = new XmlSerializer(typeof(POCD_MT000040ClinicalDocument));
            var reader = new StreamReader(path);

            var doc = (POCD_MT000040ClinicalDocument)serializer.Deserialize(reader);

            var client = doc.GetClient();
            Assert.Equal(cs, client.Gender.CodeSystem?.Value);
            Assert.Equal(csName, client.Gender.CodeSystemName);
            Assert.Equal(code, client.Gender.Value);
            Assert.Equal(nullFlavor, client.Gender.NullFlavor);
            Assert.Equal(displayName, client.Gender.DisplayName);
        }

        [Theory]
        [XmlDocumentData("TestData/CCD/1.xml", null, null, null, null, "92691", "US", "Address: Zip only 92691 (1.xml)")]
        public void GetClientSetsAddress(string path, string street1, string street2, string city, string state, string zip, string country, string testName)
        {
            var serializer = new XmlSerializer(typeof(POCD_MT000040ClinicalDocument));
            var reader = new StreamReader(path);

            var doc = (POCD_MT000040ClinicalDocument)serializer.Deserialize(reader);

            var client = doc.GetClient();
            Assert.Equal(street1, client.Address.Street1);
            Assert.Equal(street2, client.Address.Street2);
            Assert.Equal(city, client.Address.City);
            Assert.Equal(state, client.Address.State);
            Assert.Equal(zip, client.Address.Zip);
            Assert.Equal(country, client.Address.Country);
        }

        [Theory]
        [XmlDocumentData("TestData/CCD/1.xml", null, "UNK", "Language: null (1.xml)")]
        public void GetClientSetsLanguage(string path, string expected, string nullFlavor, string testName)
        {
            var serializer = new XmlSerializer(typeof(POCD_MT000040ClinicalDocument));
            var reader = new StreamReader(path);

            var doc = (POCD_MT000040ClinicalDocument)serializer.Deserialize(reader);

            var client = doc.GetClient();
            Assert.Equal(expected, client.Language.Value);
            Assert.Equal(nullFlavor, client.Language.NullFlavor);
        }

        [Theory]
        [XmlDocumentData("TestData/CCD/1.xml", null, "UNK", "Race: null (1.xml)")]
        public void GetClientSetsRace(string path, string expected, string nullFlavor, string testName)
        {
            var serializer = new XmlSerializer(typeof(POCD_MT000040ClinicalDocument));
            var reader = new StreamReader(path);

            var doc = (POCD_MT000040ClinicalDocument)serializer.Deserialize(reader);

            var client = doc.GetClient();
            Assert.Equal(expected, client.Race.Value);
            Assert.Equal(nullFlavor, client.Race.NullFlavor);
        }

        [Theory]
        [XmlDocumentData("TestData/CCD/1.xml", null, "UNK", "Ethnicity: null (1.xml)")]
        public void GetClientSetsEthnicity(string path, string expected, string nullFlavor, string testName)
        {
            var serializer = new XmlSerializer(typeof(POCD_MT000040ClinicalDocument));
            var reader = new StreamReader(path);

            var doc = (POCD_MT000040ClinicalDocument)serializer.Deserialize(reader);

            var client = doc.GetClient();
            Assert.Equal(expected, client.Ethnicity.Value);
            Assert.Equal(nullFlavor, client.Ethnicity.NullFlavor);
        }

        [Theory]
        [XmlDocumentData("TestData/CCD/1.xml", null, null, "Phone: null (1.xml)")]
        public void GetClientSetsPhone(string path, string expected, string type, string testName)
        {
            var serializer = new XmlSerializer(typeof(POCD_MT000040ClinicalDocument));
            var reader = new StreamReader(path);

            var doc = (POCD_MT000040ClinicalDocument)serializer.Deserialize(reader);

            var client = doc.GetClient();
            Assert.Equal(expected, client.Phone.Number);
            Assert.Equal(type, client.Phone.Type);
        }
    }
}