using System.IO;
using System.Linq;
using System.Xml;
using System.Xml.Serialization;
using Xunit;

namespace Ccda.Tests.R2
{
    /// <summary>
    /// Testing the classes generated by xsd cda_sdtc.xsd  SDTC.xsd /classes
    /// </summary>
    public class ParserTests
    {
        [Theory]
        [XmlDocumentData("TestData/CCD/1.xml", "Client (1.xml)")]
        [XmlDocumentData("TestData/CCD/4.xml", "Client (4.xml)")]
        [XmlDocumentData("TestData/CCD/5.xml", "Client (5.xml)")]
        [XmlDocumentData("TestData/CCD/6.xml", "Client (6.xml)")]
        [XmlDocumentData("TestData/CCD/7.xml", "Client (7.xml)")]
        [XmlDocumentData("TestData/CCD/8.xml", "Client (8.xml)")]
        [XmlDocumentData("TestData/CCD/9.xml", "Client (9.xml)")]
        public void CanParseDocument(string path, string testName)
        {
            var serializer = new XmlSerializer(typeof(POCD_MT000040ClinicalDocument));
            var reader = new StreamReader(path);

            var doc = (POCD_MT000040ClinicalDocument)serializer.Deserialize(reader);

            //doc.recordTarget.FirstOrDefault(rt => rt.patientRole != null);

            Assert.True(true, "Shouldn't throw!");
        }
    }
}